# Use keycloak base
FROM jboss/keycloak:1.9.1.Final

# Maintainer details
MAINTAINER James Falkner <jfalkner@redhat.com>

# Environment Variables 
# ENV KEYCLOAK_USER jfalkner
# ENV KEYCLOAK_PASSWORD keycloak1!

USER root

COPY support/keycloak-config.json support/keycloak-setup.sh /tmp/

# setup keycloak
RUN chmod a+x /tmp/keycloak-setup.sh 

USER jboss

RUN /tmp/keycloak-setup.sh /tmp/keycloak-config.json 

# Exposed default keycloak port
EXPOSE 8080

