sso:
        build: .
        dockerfile: Dockerfile.sso
        hostname: sso
        expose:
                - 8080
        ports:
                - "8181:8080"

coolstore:
        build: .
        dockerfile: Dockerfile.coolstore
        hostname: coolstore
        expose:
                - 9990
                - 9999
                - 8080
        ports:
                - "8080:8080"
                - "9999:9999"
                - "9990:9990"
        links:
                - sso
